import { StyleSheet, Platform } from 'react-native';
import { C } from '../constants/theme';

export const s = StyleSheet.create({
  safe:          { flex: 1, backgroundColor: C.bg },
  scroll:        { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 40 },
  header:        { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: C.white, paddingHorizontal: 18, paddingTop: Platform.OS === 'android' ? 14 : 0, paddingBottom: 14, borderBottomWidth: 1, borderBottomColor: C.border },
  headerLeft:    { flexDirection: 'row', alignItems: 'center', gap: 11 },
  headerIconWrap:{ width: 38, height: 38, borderRadius: 11, backgroundColor: C.tealLight, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: C.teal + '44' },
  headerTitle:   { color: C.dark, fontSize: 18, fontWeight: '800' },
  headerSub:     { color: C.muted, fontSize: 11, marginTop: 1 },
  overduePill:   { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: C.redLight, borderRadius: 20, paddingHorizontal: 9, paddingVertical: 5, borderWidth: 1, borderColor: C.red + '44' },
  overduePillTxt:{ color: C.red, fontSize: 11, fontWeight: '700' },
  statsRow:   { flexDirection: 'row', gap: 10, marginBottom: 12 },
  statCard:   { flex: 1, backgroundColor: C.white, borderRadius: 14, padding: 14, borderWidth: 1, borderColor: C.border, borderTopWidth: 3, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 6, elevation: 2 },
  statIcoWrap:{ width: 32, height: 32, borderRadius: 9, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  statLbl:    { color: C.muted, fontSize: 10, fontWeight: '600', letterSpacing: 0.4, textTransform: 'uppercase', marginBottom: 4 },
  statVal:    { fontSize: 20, fontWeight: '800', letterSpacing: -0.5 },
  warnBanner:   { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: C.amberLight, borderRadius: 9, borderWidth: 1, borderColor: C.amber + '55', padding: 11, marginBottom: 14 },
  warnBannerTxt:{ color: C.amber, fontSize: 12, fontWeight: '600', flex: 1 },
  secRow:    { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 10, marginTop: 4 },
  secTitle:  { color: C.mid, fontSize: 13, fontWeight: '700', flex: 1 },
  secPill:   { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
  secPillTxt:{ fontSize: 10, fontWeight: '700' },
  tableCard:{ backgroundColor: C.white, borderRadius: 14, borderWidth: 1, borderColor: C.border, marginBottom: 20, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 6, elevation: 2 },
  tableHead:{ flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 9, backgroundColor: C.slateLight, borderBottomWidth: 1, borderBottomColor: C.border },
  thTxt:    { color: C.muted, fontSize: 9, fontWeight: '700', letterSpacing: 0.8, textTransform: 'uppercase' },
  tableRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 13 },
  cdTitle:  { color: C.dark, fontSize: 14, fontWeight: '700' },
  cdArtist: { color: C.muted, fontSize: 12, marginTop: 1 },
  stockTag: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 7, borderWidth: 1 },
  stockTxt: { fontSize: 11, fontWeight: '800' },
  borrowBtn:       { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: C.teal, paddingHorizontal: 9, paddingVertical: 7, borderRadius: 8 },
  borrowBtnTxt:    { color: '#fff', fontSize: 11, fontWeight: '700' },
  borrowBtnNone:   { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: C.redLight, paddingHorizontal: 9, paddingVertical: 7, borderRadius: 8, borderWidth: 1, borderColor: C.red + '44' },
  borrowBtnNoneTxt:{ color: C.red, fontSize: 11, fontWeight: '700' },
  borrowCard:   { backgroundColor: C.white, borderRadius: 14, marginBottom: 10, borderWidth: 1, borderColor: C.border, flexDirection: 'row', overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 6, elevation: 2 },
  borrowCardRed:{ borderColor: C.red + '55' },
  stripe:       { width: 5 },
  borrowBody:   { flex: 1, padding: 13 },
  borrowTop:    { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 10 },
  borrowTitle:  { color: C.dark, fontSize: 14, fontWeight: '800', flex: 1 },
  borrowArtist: { color: C.muted, fontSize: 12, marginTop: 1 },
  infoBlock:{ gap: 5, marginBottom: 12 },
  infoRow:  { flexDirection: 'row', alignItems: 'center', gap: 5 },
  infoLbl:  { color: C.muted, fontSize: 11, width: 74 },
  infoVal:  { color: C.mid, fontSize: 11, flex: 1 },
  badge:   { flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 7, paddingVertical: 3, borderRadius: 6, borderWidth: 1 },
  badgeTxt:{ fontSize: 10, fontWeight: '700' },
  returnBtn:   { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: C.teal, borderRadius: 9, paddingVertical: 9 },
  returnBtnRed:{ backgroundColor: C.red },
  returnBtnTxt:{ color: '#fff', fontSize: 13, fontWeight: '700' },
  emptyCard: { backgroundColor: C.white, borderRadius: 14, borderWidth: 1, borderColor: C.border, padding: 36, alignItems: 'center', gap: 8, marginBottom: 12 },
  emptyTitle:{ color: C.mid, fontSize: 15, fontWeight: '700' },
  emptySub:  { color: C.muted, fontSize: 13 },
  overlay:   { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  sheet:     { backgroundColor: C.white, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 20, paddingBottom: Platform.OS === 'ios' ? 40 : 28, borderTopWidth: 1, borderTopColor: C.border },
  sheetBar:  { width: 40, height: 4, backgroundColor: C.mutedBorder, borderRadius: 2, alignSelf: 'center', marginTop: 12, marginBottom: 20 },
  sheetHd:   { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 16 },
  sheetHdIco:{ width: 40, height: 40, borderRadius: 11, backgroundColor: C.tealLight, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: C.teal + '44' },
  sheetTitle:{ color: C.dark, fontSize: 17, fontWeight: '800' },
  sheetSub:  { color: C.muted, fontSize: 12, marginTop: 2 },
  sheetClose:{ width: 32, height: 32, borderRadius: 8, backgroundColor: C.slateLight, justifyContent: 'center', alignItems: 'center' },
  preview:      { backgroundColor: C.slateLight, borderRadius: 12, borderWidth: 1, borderColor: C.border, padding: 13, marginBottom: 16, gap: 5 },
  previewStats: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  previewStat:  { flex: 1, alignItems: 'center' },
  pDivider:     { width: 1, height: 30, backgroundColor: C.border },
  pStatLbl:     { color: C.muted, fontSize: 9, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 3 },
  pStatVal:     { fontSize: 13, fontWeight: '800' },
  previewDue:   { flexDirection: 'row', alignItems: 'center', gap: 5, borderTopWidth: 1, borderTopColor: C.border, paddingTop: 9 },
  previewDueTxt:{ color: C.amber, fontSize: 12, fontWeight: '600' },
  penaltyBox:{ flexDirection: 'row', alignItems: 'center', borderRadius: 12, borderWidth: 1, padding: 14, marginBottom: 20 },
  penaltyAmt:{ fontSize: 16, fontWeight: '800' },
  penaltySub:{ color: C.slate, fontSize: 12, marginTop: 3 },
  inputLbl:  { color: C.muted, fontSize: 9, fontWeight: '700', letterSpacing: 1, textTransform: 'uppercase', marginBottom: 6 },
  inputWrap: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.slateLight, borderRadius: 10, borderWidth: 1, borderColor: C.mutedBorder, paddingHorizontal: 13, paddingVertical: 11, marginBottom: 18 },
  inputField:{ flex: 1, color: C.dark, fontSize: 14 },
  btnRow:      { flexDirection: 'row', gap: 10 },
  btnCancel:   { flex: 1, borderRadius: 10, paddingVertical: 12, alignItems: 'center', borderWidth: 1, borderColor: C.mutedBorder, maxHeight: 46 },
  btnCancelTxt:{ color: C.slate, fontWeight: '600', fontSize: 13 },
  btnConfirm:  { flex: 1, backgroundColor: C.teal, borderRadius: 10, paddingVertical: 12, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', maxHeight: 46 },
  btnConfirmTxt:{ color: '#fff', fontWeight: '800', fontSize: 13 },
  btnOff:      { opacity: 0.35 },
});
